#include <iostream>
using namespace std;

int main(){
    cout<< "|----Start\n";
    cout<< "|\n";
    cout<< "|----Bank Clerk Login\n";
    cout<< "|\n";
    cout<< "|-- Bank Clerk Operations --|\n";
    cout<< "|    |\n";
    cout<< "|    |-- Add a customer -------------|\n";
    cout<< "|    |    |\n";
    cout<< "|    |    |-- Enter customer details |\n";
    cout<< "|    |    |-- Save details           |\n";
    cout<< "|    |    |-- Confirmation message   |\n";
    cout<< "|    |\n";
    cout<< "|    |-- Delete a customer ----------|\n";
    cout<< "|    |    |\n";
    cout<< "|    |    |-- Enter customer ID      |\n";
    cout<< "|    |    |-- Search for customer    |\n";
    cout<< "|    |    |-- Delete customer record |\n";
    cout<< "|    |    |-- Confirmation message   |\n";
    cout<< "|    |\n";
    cout<< "|    |-- Modify a customer's details |\n";
    cout<< "|    |    |\n";
    cout<< "|    |    |-- Enter customer ID      |\n";
    cout<< "|    |    |-- Search for customer    |\n";
    cout<< "|    |    |-- Modify details         |\n";
    cout<< "|    |    |-- Save changes           |\n";
    cout<< "|    |    |-- Confirmation message   |\n";
    cout<< "|    |\n";
    cout<< "|    |-- Credit money to account ----|\n";
    cout<< "|    |    |\n";
    cout<< "|    |    |-- Enter customer ID      |\n";
    cout<< "|    |    |-- Search for customer    |\n";
    cout<< "|    |    |-- Enter amount to credit |\n";
    cout<< "|    |    |-- Update account balance |\n";
    cout<< "|    |    |-- Confirmation message   |\n";
    cout<< "|    |\n";
    cout<< "|    |-- Debit money from account ---|\n";
    cout<< "|    |    |\n";
    cout<< "|    |    |-- Enter customer ID      |\n";
    cout<< "|    |    |-- Search for customer    |\n";
    cout<< "|    |    |-- Enter amount to debit  |\n";
    cout<< "|    |    |-- Update account balance |\n";
    cout<< "|    |    |-- Confirmation message   |\n";
    cout<< "|    |\n";
    cout<< "|    |-- Query on account ----|\n";
    cout<< "|    |    |\n";
    cout<< "|    |    |-- View all customers     |\n";
    cout<< "|    |    |-- Enter customer ID      |\n";
    cout<< "|    |    |-- Search for customer    |\n";
    cout<< "|    |    |-- Display report         |\n";
    cout<< "|    |\n";
    cout<< "|    |-- Quit Application -----------|\n";
    cout<< "|         |\n";
    cout<< "|         |-- Close all files, etc.  |\n";
    cout<< "|         |-- Exit program           |\n";
    cout<< "|\n";
    cout<< "|----Customer Login\n";
    cout<< "|\n";
    cout<< "|-- Customer Operations --|\n";
    cout<< "|\n";
    cout<< "|-- View customer details ---------|\n";
    cout<< "|    |\n";
    cout<< "|    |-- Enter customer ID         |\n";
    cout<< "|    |-- Retrieve customer details |\n";
    cout<< "|    |-- Display customer details  |\n";
    cout<< "|\n";
    cout<< "|-- Transfer money ----------------|\n";
    cout<< "|    |\n";
    cout<< "|    |-- Enter source ID and Destination ID |\n";
    cout<< "|    |-- Enter transfer amount      |\n";
    cout<< "|    |-- Update account balances    |\n";
    cout<< "|    |-- Confirmation message       |\n";
    cout<< "|\n";
    cout<< "|-- Query/Report on account --------|\n";
    cout<< "|    |\n";
    cout<< "|    |-- Enter account Number       |\n";
    cout<< "|    |-- Retrieve account details   |\n";
    cout<< "|    |-- Generate transaction report|\n";
    cout<< "|    |-- Display report             |\n";
    cout<< "|\n";
    cout<< "|-- Quit Application ---------------|\n";
    cout<< "|    |\n";
    cout<< "|    |-- Close all files, etc.    |\n";
    cout<< "|    |-- Exit program             |\n";
    cout<< "|\n";
    cout<< "|----End\n";

    return 0;
}
